on: 
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Do some work
        run: echo test!!!
      - name: Fail manually
        run: exit 1
